# Generated by Django 4.2.7 on 2023-11-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qrcode_image',
        ),
    ]
