# Generated by Django 4.2.7 on 2023-11-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0002_remove_qrcode_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
