# Generated by Django 4.2.7 on 2023-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0003_qrcode_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_code_image_jpg',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/jpg/'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_code_image_svg',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/svg/'),
        ),
    ]
